version: "2"
services:
  api:
    container_name: "boleto-api"
    build: .
    volumes:
     - ~/boletodb/upMongo:/home/upMongo
     - ~/boleto_cert:/home/mundipagg/boleto_cert
    ports:
     - "9000:3000"
    environment:
     - API_PORT=3000
     - API_VERSION=0.0.2
     - ENVIRONMENT=Production
     - SEQ_URL=http://log.mundi.local
     - SEQ_API_KEY=Wr1g3bzkuMcCyKYyy1UW
     - ENABLE_REQUEST_LOG=false
     - ENABLE_PRINT_REQUEST=true
     - URL_BB_REGISTER_BOLETO=https://cobranca.bb.com.br:7101/registrarBoleto
     - URL_BB_TOKEN=https://oauth.bb.com.br/oauth/token
     - MONGODB_URL=172.17.153.33:27017
     - APP_URL=https://boleto.mundipagg.com/boleto
     - BOLETO_JSON_STORE=/home/upMongo
     - URL_CAIXA=https://barramento.caixa.gov.br/sibar/ManutencaoCobrancaBancaria/Boleto/Externo
     - URL_CITI=https://citigroupsoa.citigroup.com/comercioeletronico/registerboleto/RegisterBoletoSOAP
     - URL_CITI_BOLETO=https://corporate.brazil.citibank.com/ebillpayer/jspInformaDadosConsulta.jsp
     - CERT_BOLETO_CRT=/home/mundipagg/boleto_cert/certificate.crt
     - CERT_BOLETO_KEY=/home/mundipagg/boleto_cert/mundi.key
     - CERT_BOLETO_CA=/home/mundipagg/boleto_cert/ca-cert.ca
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ~/boletodb/db:/data/db
      - ~/boletodb/configdb:/data/configdb
      - ~/dump_boletodb:/dump/boletoapi
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
  nginx:
    image: nginx:latest
    container_name: "balance"
    ports:
      - "443:443"
    volumes:
      - ~/boleto_ssh:/etc/nginx
