language: go

go:
  - 1.8.x
  - tip

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

before_install:
  - glide install

script:
  - ./travis_test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
