language: go

go:
  - 1.8.x
  - tip

before_install:
  - curl https://glide.sh/get | sh
  - glide install

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
